name: Bug Report
description: You think somethings is broken or not working as expected
title: "[Bug]: "
labels: ["bug-report"]

body:
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, also fill every dropdown options and *provide screenshots if possible**
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: Please tell us what happened in a very clear and simple way
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Please provide **full** cmd/terminal logs from the moment there is an error (usually starts with 'Traceback'), after your bug happened. If it's very long, provide a link to pastebin or similar service.
      render: shell
  - type: textarea
    id: model
    attributes:
      label: Which colab and model(s) were you using when the error occurred?
      description: Please enter the colab and model(s) link.
      placeholder: |
        https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/lite/stable_diffusion_webui_colab.ipynb
        https://civitai.com/models/6755/cetus-mix
        https://civitai.com/models/8217/fashion-girl
        https://civitai.com/models/12597/moxin
    validations:
      required: true
  - type: dropdown
    id: link
    attributes:
      label: Which Public WebUI Colab URL were you using when the error occurred?
      description: Public WebUI Colab URL
      options:
        - remote.moe
        - gradio.live
        - lhr.life
        - trycloudflare.com
    validations:
      required: true
  - type: textarea
    id: png-info
    attributes:
      label: If you used HiRes mode when the error occurred, please provide the Hires info
      description: Upscaler, Hires steps, Denoising strength, Upscale by ...
      placeholder: |
        Hires upscale: 2.85, Hires upscaler: R-ESRGAN 4x+
    validations:
      required: false
